# Generated by Django 6.1 on 2026-08-18 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_published_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.like'),
        ),
    ]
